-- Seed all product categories (3 levels).
-- Inserts are ordered parents-before-children to satisfy the self-referencing FK.
-- ON CONFLICT DO NOTHING makes this idempotent if re-run.
-- The FK on items.category is added at the bottom after all seed data is present.

-- ── Level 1: top-level categories ────────────────────────────────────────────
insert into public.categories (slug, label, sort_order) values
  ('announcements',          'Announcements',             1),
  ('audio',                  'Audio',                     2),
  ('auto-accessories',       'Auto Accessories',          3),
  ('babies-kids',            'Babies & Kids',             4),
  ('beauty-personal-care',   'Beauty & Personal Care',    5),
  ('cars',                   'Cars',                      6),
  ('community',              'Community',                 7),
  ('computers-tech',         'Computers & Tech',          8),
  ('everything-else',        'Everything Else',           9),
  ('food-drinks',            'Food & Drinks',             10),
  ('furniture-home-living',  'Furniture & Home Living',   11),
  ('health-nutrition',       'Health & Nutrition',        12),
  ('hobbies-toys',           'Hobbies & Toys',            13),
  ('jobs',                   'Jobs',                      14),
  ('looking-for',            'Looking For',               15),
  ('luxury',                 'Luxury',                    16),
  ('mens-fashion',           'Men''s Fashion',            17),
  ('mobile-phones-gadgets',  'Mobile Phones & Gadgets',   18),
  ('motorbikes',             'Motorbikes',                19),
  ('pet-supplies',           'Pet Supplies',              20),
  ('photography',            'Photography',               21),
  ('property',               'Property',                  22),
  ('services',               'Services',                  23),
  ('sports-equipment',       'Sports Equipment',          24),
  ('tv-home-appliances',     'TV & Home Appliances',      25),
  ('tickets-vouchers',       'Tickets & Vouchers',        26),
  ('video-gaming',           'Video Gaming',              27),
  ('womens-fashion',         'Women''s Fashion',          28)
on conflict (slug) do nothing;

-- ── Level 2: subcategories ───────────────────────────────────────────────────
insert into public.categories (slug, label, parent_slug) values
  -- audio
  ('earphones',                        'Earphones',                       'audio'),
  ('headphones-headsets',              'Headphones & Headsets',           'audio'),
  ('microphones',                      'Microphones',                     'audio'),
  ('audio-other-equipment',            'Other Audio Equipment',           'audio'),
  ('portable-audio-accessories',       'Portable Audio Accessories',      'audio'),
  ('portable-music-players',           'Portable Music Players',          'audio'),
  ('soundbars-speakers-amplifiers',    'Soundbars, Speakers & Amplifiers','audio'),
  ('voice-recorders',                  'Voice Recorders',                 'audio'),
  -- babies-kids
  ('babies-kids-fashion',              'Babies & Kids Fashion',           'babies-kids'),
  ('baby-monitors',                    'Baby Monitors',                   'babies-kids'),
  ('baby-nursery-kids-furniture',      'Baby Nursery & Kids Furniture',   'babies-kids'),
  ('bathing-changing',                 'Bathing & Changing',              'babies-kids'),
  ('going-out',                        'Going Out',                       'babies-kids'),
  ('infant-playtime',                  'Infant Playtime',                 'babies-kids'),
  ('maternity-care',                   'Maternity Care',                  'babies-kids'),
  ('nursing-feeding',                  'Nursing & Feeding',               'babies-kids'),
  -- beauty-personal-care
  ('bath-body',                        'Bath & Body',                     'beauty-personal-care'),
  ('ear-care',                         'Ear Care',                        'beauty-personal-care'),
  ('face',                             'Face',                            'beauty-personal-care'),
  ('foot-care',                        'Foot Care',                       'beauty-personal-care'),
  ('fragrance-deodorants',             'Fragrance & Deodorants',          'beauty-personal-care'),
  ('hair',                             'Hair',                            'beauty-personal-care'),
  ('hands-nails',                      'Hands & Nails',                   'beauty-personal-care'),
  ('mens-grooming',                    'Men''s Grooming',                 'beauty-personal-care'),
  ('oral-care',                        'Oral Care',                       'beauty-personal-care'),
  ('sanitary-hygiene',                 'Sanitary Hygiene',                'beauty-personal-care'),
  ('sanitisers-disinfectants',         'Sanitisers & Disinfectants',      'beauty-personal-care'),
  ('vision-care',                      'Vision Care',                     'beauty-personal-care'),
  -- cars
  ('cars-for-sale',                    'Cars for Sale',                   'cars'),
  ('vehicle-rentals',                  'Vehicle Rentals',                 'cars'),
  -- computers-tech
  ('desktops',                         'Desktops',                        'computers-tech'),
  ('laptops-notebooks',                'Laptops & Notebooks',             'computers-tech'),
  ('office-business-technology',       'Office & Business Technology',    'computers-tech'),
  ('computers-tech-parts-accessories', 'Parts & Accessories',             'computers-tech'),
  ('printers-scanners-copiers',        'Printers, Scanners & Copiers',    'computers-tech'),
  -- everything-else
  ('others',                           'Others',                          'everything-else'),
  -- food-drinks
  ('beverages',                        'Beverages',                       'food-drinks'),
  ('chilled-frozen-food',              'Chilled & Frozen Food',           'food-drinks'),
  ('fresh-produce',                    'Fresh Produce',                   'food-drinks'),
  ('gift-baskets-hampers',             'Gift Baskets & Hampers',          'food-drinks'),
  ('homemade-bakes',                   'Homemade Bakes',                  'food-drinks'),
  ('local-eats',                       'Local Eats',                      'food-drinks'),
  ('food-drinks-other',                'Other Food & Drinks',             'food-drinks'),
  ('packaged-instant-food',            'Packaged & Instant Food',         'food-drinks'),
  ('rice-noodles',                     'Rice & Noodles',                  'food-drinks'),
  ('spice-seasoning',                  'Spice & Seasoning',               'food-drinks'),
  -- furniture-home-living
  ('bathroom-kitchen-fixtures',        'Bathroom & Kitchen Fixtures',     'furniture-home-living'),
  ('bedding-towels',                   'Bedding & Towels',                'furniture-home-living'),
  ('cleaning-homecare-supplies',       'Cleaning & Homecare Supplies',    'furniture-home-living'),
  ('furniture',                        'Furniture',                       'furniture-home-living'),
  ('gardening',                        'Gardening',                       'furniture-home-living'),
  ('home-decor',                       'Home Decor',                      'furniture-home-living'),
  ('home-fragrance',                   'Home Fragrance',                  'furniture-home-living'),
  ('home-improvement-organisation',    'Home Improvement & Organisation', 'furniture-home-living'),
  ('kitchenware-tableware',            'Kitchenware & Tableware',         'furniture-home-living'),
  ('lighting-fans',                    'Lighting & Fans',                 'furniture-home-living'),
  ('outdoor-furniture',                'Outdoor Furniture',               'furniture-home-living'),
  ('security-locks',                   'Security & Locks',                'furniture-home-living'),
  -- health-nutrition
  ('assistive-rehabilatory-aids',      'Assistive & Rehabilatory Aids',   'health-nutrition'),
  ('braces-support-protection',        'Braces, Support & Protection',    'health-nutrition'),
  ('face-masks-shields',               'Face Masks & Face Shields',       'health-nutrition'),
  ('health-monitors-weighing-scales',  'Health Monitors & Weighing Scales','health-nutrition'),
  ('health-supplements',               'Health Supplements',              'health-nutrition'),
  ('insect-repellent',                 'Insect Repellent',                'health-nutrition'),
  ('massage-devices',                  'Massage Devices',                 'health-nutrition'),
  ('medical-supplies-tools',           'Medical Supplies & Tools',        'health-nutrition'),
  ('thermometers',                     'Thermometers',                    'health-nutrition'),
  -- hobbies-toys
  ('books-magazines',                  'Books & Magazines',               'hobbies-toys'),
  ('collectibles-memorabilia',         'Collectibles & Memorabilia',      'hobbies-toys'),
  ('music-media',                      'Music & Media',                   'hobbies-toys'),
  ('stationery-craft',                 'Stationery & Craft',              'hobbies-toys'),
  ('toys-games',                       'Toys & Games',                    'hobbies-toys'),
  ('travel',                           'Travel',                          'hobbies-toys'),
  -- jobs
  ('full-time',                        'Full-time',                       'jobs'),
  ('internships-others',               'Internships & Others',            'jobs'),
  ('part-time',                        'Part-time',                       'jobs'),
  -- luxury
  ('luxury-accessories',               'Accessories',                     'luxury'),
  ('luxury-apparel',                   'Apparel',                         'luxury'),
  ('luxury-bags-wallets',              'Bags & Wallets',                  'luxury'),
  ('luxury-sneakers-footwear',         'Sneakers & Footwear',             'luxury'),
  ('luxury-watches',                   'Watches',                         'luxury'),
  -- mens-fashion
  ('mens-activewear',                  'Activewear',                      'mens-fashion'),
  ('mens-bags',                        'Bags',                            'mens-fashion'),
  ('mens-bottoms',                     'Bottoms',                         'mens-fashion'),
  ('mens-coats-jackets-outerwear',     'Coats, Jackets and Outerwear',    'mens-fashion'),
  ('mens-footwear',                    'Footwear',                        'mens-fashion'),
  ('mens-muslim-wear',                 'Muslim Wear',                     'mens-fashion'),
  ('mens-tops-sets',                   'Tops & Sets',                     'mens-fashion'),
  ('mens-watches-accessories',         'Watches & Accessories',           'mens-fashion'),
  -- mobile-phones-gadgets
  ('e-readers',                        'E-Readers',                       'mobile-phones-gadgets'),
  ('mobile-gadget-accessories',        'Mobile & Gadget Accessories',     'mobile-phones-gadgets'),
  ('mobile-phones',                    'Mobile Phones',                   'mobile-phones-gadgets'),
  ('other-gadgets',                    'Other Gadgets',                   'mobile-phones-gadgets'),
  ('tablets',                          'Tablets',                         'mobile-phones-gadgets'),
  ('walkie-talkie',                    'Walkie-Talkie',                   'mobile-phones-gadgets'),
  ('wearables-smart-watches',          'Wearables & Smart Watches',       'mobile-phones-gadgets'),
  -- pet-supplies
  ('pet-health-grooming',              'Health & Grooming',               'pet-supplies'),
  ('pet-homes-accessories',            'Homes & Other Pet Accessories',   'pet-supplies'),
  ('pet-food',                         'Pet Food',                        'pet-supplies'),
  -- photography
  ('cameras',                          'Cameras',                         'photography'),
  ('drones',                           'Drones',                          'photography'),
  ('lens-kits',                        'Lens & Kits',                     'photography'),
  ('photography-accessories',          'Photography Accessories',         'photography'),
  ('video-cameras',                    'Video Cameras',                   'photography'),
  -- property
  ('property-for-sale',                'For Sale',                        'property'),
  ('property-others',                  'Others',                          'property'),
  ('property-rentals',                 'Rentals',                         'property'),
  -- services
  ('beauty-services',                  'Beauty Services',                 'services'),
  ('electronics-gadget-repairs',       'Electronics & Gadget Repairs',    'services'),
  ('home-services',                    'Home Services',                   'services'),
  ('services-others',                  'Others',                          'services'),
  -- sports-equipment
  ('bicycles-parts',                   'Bicycles & Parts',                'sports-equipment'),
  ('exercise-fitness',                 'Exercise & Fitness',              'sports-equipment'),
  ('fishing',                          'Fishing',                         'sports-equipment'),
  ('hiking-camping',                   'Hiking & Camping',                'sports-equipment'),
  ('sports-other',                     'Other Sports Equipment and Supplies','sports-equipment'),
  ('sports-games',                     'Sports & Games',                  'sports-equipment'),
  -- tv-home-appliances
  ('air-conditioners-heating',         'Air Conditioners & Heating',      'tv-home-appliances'),
  ('air-purifiers-dehumidifiers',      'Air Purifiers & Dehumidifiers',   'tv-home-appliances'),
  ('electrical-adaptors-sockets',      'Electrical, Adaptors & Sockets',  'tv-home-appliances'),
  ('irons-steamers',                   'Irons & Steamers',                'tv-home-appliances'),
  ('kitchen-appliances',               'Kitchen Appliances',              'tv-home-appliances'),
  ('home-appliances-other',            'Other Home Appliances',           'tv-home-appliances'),
  ('tv-entertainment',                 'TV & Entertainment',              'tv-home-appliances'),
  ('vacuum-cleaner-housekeeping',      'Vacuum Cleaner & Housekeeping',   'tv-home-appliances'),
  ('washing-machines-dryers',          'Washing Machines and Dryers',     'tv-home-appliances'),
  ('water-heater-instant-showers',     'Water Heater & Instant Showers',  'tv-home-appliances'),
  -- tickets-vouchers
  ('event-tickets',                    'Event Tickets',                   'tickets-vouchers'),
  ('flights-overseas-attractions',     'Flights & Overseas Attractions',  'tickets-vouchers'),
  ('local-attractions-transport',      'Local Attractions and Transport', 'tickets-vouchers'),
  ('store-credits',                    'Store Credits',                   'tickets-vouchers'),
  ('vouchers',                         'Vouchers',                        'tickets-vouchers'),
  -- video-gaming
  ('gaming-accessories',               'Gaming Accessories',              'video-gaming'),
  ('video-game-consoles',              'Video Game Consoles',             'video-gaming'),
  ('video-games',                      'Video Games',                     'video-gaming'),
  -- womens-fashion
  ('womens-activewear',                'Activewear',                      'womens-fashion'),
  ('womens-bags-wallets',              'Bags & Wallets',                  'womens-fashion'),
  ('womens-bottoms',                   'Bottoms',                         'womens-fashion'),
  ('womens-coats-jackets-outerwear',   'Coats, Jackets and Outerwear',    'womens-fashion'),
  ('womens-dresses-sets',              'Dresses & Sets',                  'womens-fashion'),
  ('womens-footwear',                  'Footwear',                        'womens-fashion'),
  ('womens-jewelry-organisers',        'Jewelry & Organisers',            'womens-fashion'),
  ('womens-maternity-wear',            'Maternity wear',                  'womens-fashion'),
  ('womens-muslimah-fashion',          'Muslimah Fashion',                'womens-fashion'),
  ('womens-new-undergarments-loungewear','New Undergarments & Loungewear','womens-fashion'),
  ('womens-swimwear',                  'Swimwear',                        'womens-fashion'),
  ('womens-tops',                      'Tops',                            'womens-fashion'),
  ('womens-watches-accessories',       'Watches & Accessories',           'womens-fashion')
on conflict (slug) do nothing;

-- ── Level 3: leaf categories ─────────────────────────────────────────────────
insert into public.categories (slug, label, parent_slug) values
  -- baby-nursery-kids-furniture
  ('bed-guards',                       'Bed Guards',                      'baby-nursery-kids-furniture'),
  ('changing-tables-stations',         'Changing Tables & Stations',      'baby-nursery-kids-furniture'),
  ('childrens-beds',                   'Childrens'' Beds',                'baby-nursery-kids-furniture'),
  ('cots-cribs',                       'Cots & Cribs',                    'baby-nursery-kids-furniture'),
  ('kids-tables-chairs',               'Kids'' Tables & Chairs',          'baby-nursery-kids-furniture'),
  ('kids-wardrobes-storage',           'Kids'' Wardrobes & Storage',      'baby-nursery-kids-furniture'),
  ('nursery-lighting-decor',           'Nursery Lighting & Decor',        'baby-nursery-kids-furniture'),
  ('nursery-other',                    'Other Kids Furniture',            'baby-nursery-kids-furniture'),
  ('safety-gates-locks-protectors',    'Safety Gates, Locks & Protectors','baby-nursery-kids-furniture'),
  -- bathing-changing
  ('baby-toiletries-grooming',         'Baby Toiletries & Grooming',      'bathing-changing'),
  ('bathtub-bath-accessories',         'Bathtub & Bath Accessories',      'bathing-changing'),
  ('changing-mats-accessories',        'Changing Mats & Accessories',     'bathing-changing'),
  ('diapers-baby-wipes',               'Diapers & Baby Wipes',            'bathing-changing'),
  ('bathing-other',                    'Other Baby Bathing & Changing Needs','bathing-changing'),
  ('toilet-training',                  'Toilet Training',                 'bathing-changing'),
  -- going-out
  ('car-seats',                        'Car Seats',                       'going-out'),
  ('carriers-slings',                  'Carriers & Slings',               'going-out'),
  ('diaper-bags-wetbags',              'Diaper Bags & Wetbags',           'going-out'),
  ('going-out-other',                  'Other Babies Going Out Needs',    'going-out'),
  ('strollers',                        'Strollers',                       'going-out'),
  -- nursing-feeding
  ('baby-high-chairs',                 'Baby High Chairs',                'nursing-feeding'),
  ('breastfeeding-bottle-feeding',     'Breastfeeding & Bottle Feeding',  'nursing-feeding'),
  ('soothers-pacifiers',               'Soothers & Pacifiers',            'nursing-feeding'),
  ('weaning-toddler-feeding',          'Weaning & Toddler Feeding',       'nursing-feeding'),
  -- bath-body
  ('bath',                             'Bath',                            'bath-body'),
  ('body-care',                        'Body Care',                       'bath-body'),
  ('hair-removal',                     'Hair Removal',                    'bath-body'),
  -- face
  ('face-care',                        'Face Care',                       'face'),
  ('makeup',                           'Makeup',                          'face'),
  -- computers-tech-parts-accessories
  ('cables-adaptors',                  'Cables & Adaptors',               'computers-tech-parts-accessories'),
  ('chargers',                         'Chargers',                        'computers-tech-parts-accessories'),
  ('computer-keyboard',                'Computer Keyboard',               'computers-tech-parts-accessories'),
  ('computer-parts',                   'Computer Parts',                  'computers-tech-parts-accessories'),
  ('hard-disks-thumbdrives',           'Hard Disks & Thumbdrives',        'computers-tech-parts-accessories'),
  ('laptop-bags-sleeves',              'Laptop Bags & Sleeves',           'computers-tech-parts-accessories'),
  ('monitor-screens',                  'Monitor Screens',                 'computers-tech-parts-accessories'),
  ('mouse-mousepads',                  'Mouse & Mousepads',               'computers-tech-parts-accessories'),
  ('networking',                       'Networking',                      'computers-tech-parts-accessories'),
  ('computers-accessories-other',      'Other Accessories',               'computers-tech-parts-accessories'),
  ('software',                         'Software',                        'computers-tech-parts-accessories'),
  ('webcams',                          'Webcams',                         'computers-tech-parts-accessories'),
  -- cleaning-homecare-supplies
  ('cleaning-tools-supplies',          'Cleaning Tools & Supplies',       'cleaning-homecare-supplies'),
  ('detergents',                       'Detergents',                      'cleaning-homecare-supplies'),
  ('ironing-boards',                   'Ironing Boards',                  'cleaning-homecare-supplies'),
  ('pest-control',                     'Pest Control',                    'cleaning-homecare-supplies'),
  ('waste-bins-bags',                  'Waste Bins & Bags',               'cleaning-homecare-supplies'),
  -- furniture (subcategory under furniture-home-living)
  ('bed-frames-mattresses',            'Bed Frames & Mattresses',         'furniture'),
  ('chairs',                           'Chairs',                          'furniture'),
  ('home-furniture-other',             'Other Home Furniture',            'furniture'),
  ('shelves-cabinets-racks',           'Shelves, Cabinets & Racks',       'furniture'),
  ('sofas',                            'Sofas',                           'furniture'),
  ('tv-consoles',                      'TV Consoles',                     'furniture'),
  ('tables-sets',                      'Tables & Sets',                   'furniture'),
  -- gardening
  ('garden-soil-fertilisers',          'Garden Soil & Fertilisers',       'gardening'),
  ('gardening-tools-ornaments',        'Gardening Tools & Ornaments',     'gardening'),
  ('grass-mowers-trimmers',            'Grass Mowers & Trimmers',         'gardening'),
  ('hose-watering-devices',            'Hose and Watering Devices',       'gardening'),
  ('plants-seeds',                     'Plants & Seeds',                  'gardening'),
  ('pots-planters',                    'Pots & Planters',                 'gardening'),
  -- home-decor
  ('artificial-plants-flowers',        'Artificial Plants & Flowers',     'home-decor'),
  ('carpets-mats-flooring',            'Carpets, Mats & Flooring',        'home-decor'),
  ('clocks',                           'Clocks',                          'home-decor'),
  ('curtains-blinds',                  'Curtains & Blinds',               'home-decor'),
  ('cushions-throws',                  'Cushions & Throws',               'home-decor'),
  ('frames-pictures',                  'Frames & Pictures',               'home-decor'),
  ('mirrors',                          'Mirrors',                         'home-decor'),
  ('home-decor-other',                 'Other Home Decor',                'home-decor'),
  ('vases-decorative-bowls',           'Vases & Decorative Bowls',        'home-decor'),
  ('wall-decor',                       'Wall Decor',                      'home-decor'),
  -- home-improvement-organisation
  ('clothes-drying-rack',              'Clothes Drying Rack',             'home-improvement-organisation'),
  ('home-improvement-tools-accessories','Home Improvement Tools & Accessories','home-improvement-organisation'),
  ('hooks-hangers',                    'Hooks & Hangers',                 'home-improvement-organisation'),
  ('ladders-steps',                    'Ladders & Steps',                 'home-improvement-organisation'),
  ('laundry-baskets',                  'Laundry Baskets',                 'home-improvement-organisation'),
  ('storage-boxes-baskets',            'Storage Boxes & Baskets',         'home-improvement-organisation'),
  -- kitchenware-tableware
  ('bakeware',                         'Bakeware',                        'kitchenware-tableware'),
  ('coffee-tea-tableware',             'Coffee & Tea Tableware',          'kitchenware-tableware'),
  ('cookware-accessories',             'Cookware & Accessories',          'kitchenware-tableware'),
  ('dinnerware-cutlery',               'Dinnerware & Cutlery',            'kitchenware-tableware'),
  ('food-organisation-storage',        'Food Organisation & Storage',     'kitchenware-tableware'),
  ('knives-chopping-boards',           'Knives & Chopping Boards',        'kitchenware-tableware'),
  ('kitchenware-other',                'Other Kitchenware & Tableware',   'kitchenware-tableware'),
  ('pitchers-dispensers',              'Pitchers & Dispensers',           'kitchenware-tableware'),
  ('table-linen-textiles',             'Table Linen & Textiles',          'kitchenware-tableware'),
  ('towels-napkins-holders',           'Towels, Napkins & Holders',       'kitchenware-tableware'),
  ('water-bottles-tumblers',           'Water Bottles & Tumblers',        'kitchenware-tableware'),
  -- lighting-fans
  ('fans',                             'Fans',                            'lighting-fans'),
  ('lighting',                         'Lighting',                        'lighting-fans'),
  -- security-locks
  ('locks-doors-gates',                'Locks, Doors & Gates',            'security-locks'),
  ('security-other',                   'Other Security Devices',          'security-locks'),
  ('peephole-viewers-doorbells',       'Peephole Viewers & Doorbells',    'security-locks'),
  ('safe',                             'Safe',                            'security-locks'),
  ('security-systems-cctv',            'Security Systems & CCTV Cameras', 'security-locks'),
  -- assistive-rehabilatory-aids
  ('adult-incontinence',               'Adult Incontinence',              'assistive-rehabilatory-aids'),
  ('assistive-aids-other',             'Other Assistive Aids',            'assistive-rehabilatory-aids'),
  ('rehabilitative-devices',           'Rehabilitative Devices',          'assistive-rehabilatory-aids'),
  ('visual-hearing-aids',              'Visual & Hearing Aids',           'assistive-rehabilatory-aids'),
  ('wheelchairs',                      'Wheelchairs',                     'assistive-rehabilatory-aids'),
  -- health-supplements
  ('health-food-drinks-tonics',        'Health Food, Drinks & Tonics',    'health-supplements'),
  ('sports-fitness-nutrition',         'Sports & Fitness Nutrition',      'health-supplements'),
  ('vitamins-supplements',             'Vitamins & Supplements',          'health-supplements'),
  -- books-magazines
  ('assessment-books',                 'Assessment Books',                'books-magazines'),
  ('childrens-books',                  'Children''s Books',               'books-magazines'),
  ('comics-manga',                     'Comics & Manga',                  'books-magazines'),
  ('magazines',                        'Magazines',                       'books-magazines'),
  ('religion-books',                   'Religion Books',                  'books-magazines'),
  ('storybooks',                       'Storybooks',                      'books-magazines'),
  ('textbooks',                        'Textbooks',                       'books-magazines'),
  ('travel-holiday-guides',            'Travel & Holiday Guides',         'books-magazines'),
  -- collectibles-memorabilia
  ('currency',                         'Currency',                        'collectibles-memorabilia'),
  ('fan-merchandise',                  'Fan Merchandise',                 'collectibles-memorabilia'),
  ('j-pop',                            'J-pop',                           'collectibles-memorabilia'),
  ('k-wave',                           'K-Wave',                         'collectibles-memorabilia'),
  ('religious-items',                  'Religious Items',                 'collectibles-memorabilia'),
  ('stamps-prints',                    'Stamps & Prints',                 'collectibles-memorabilia'),
  ('vintage-collectibles',             'Vintage Collectibles',            'collectibles-memorabilia'),
  -- music-media
  ('cds-dvds',                         'CDs & DVDs',                      'music-media'),
  ('music-accessories',                'Music Accessories',               'music-media'),
  ('music-scores',                     'Music Scores',                    'music-media'),
  ('musical-instruments',              'Musical Instruments',             'music-media'),
  ('vinyls',                           'Vinyls',                          'music-media'),
  -- stationery-craft
  ('art-prints',                       'Art & Prints',                    'stationery-craft'),
  ('craft-supplies-tools',             'Craft Supplies & Tools',          'stationery-craft'),
  ('flowers-bouquets',                 'Flowers & Bouquets',              'stationery-craft'),
  ('handmade-craft',                   'Handmade Craft',                  'stationery-craft'),
  ('occasions-party-supplies',         'Occasions & Party Supplies',      'stationery-craft'),
  ('stationery-craft-other',           'Other Stationery & Craft',        'stationery-craft'),
  ('stationery-school-supplies',       'Stationery & School Supplies',    'stationery-craft'),
  -- travel (under hobbies-toys)
  ('luggages',                         'Luggages',                        'travel'),
  ('travel-essentials-accessories',    'Travel Essentials & Accessories', 'travel'),
  ('umbrellas',                        'Umbrellas',                       'travel'),
  -- full-time jobs
  ('full-time-admin',                  'Admin, Office & Finance',         'full-time'),
  ('full-time-cleaning',               'Cleaning & Housekeeping',         'full-time'),
  ('full-time-computer-it',            'Computer & IT',                   'full-time'),
  ('full-time-customer-service',       'Customer Service',                'full-time'),
  ('full-time-drivers',                'Drivers & Delivery',              'full-time'),
  ('full-time-events',                 'Events',                          'full-time'),
  ('full-time-hospitality',            'Hospitality, F&B',                'full-time'),
  ('full-time-others',                 'Others',                          'full-time'),
  ('full-time-sales',                  'Sales, Retail & Marketing',       'full-time'),
  ('full-time-security',               'Security',                        'full-time'),
  ('full-time-warehouse',              'Warehouse & Logistics',           'full-time'),
  -- part-time jobs
  ('part-time-admin',                  'Admin, Office & Finance',         'part-time'),
  ('part-time-cleaning',               'Cleaning & Housekeeping',         'part-time'),
  ('part-time-computer-it',            'Computer & IT',                   'part-time'),
  ('part-time-customer-service',       'Customer Service',                'part-time'),
  ('part-time-drivers',                'Drivers & Delivery',              'part-time'),
  ('part-time-events',                 'Events',                          'part-time'),
  ('part-time-hospitality',            'Hospitality, F&B',                'part-time'),
  ('part-time-others',                 'Others',                          'part-time'),
  ('part-time-sales',                  'Sales, Retail & Marketing',       'part-time'),
  ('part-time-security',               'Security',                        'part-time'),
  ('part-time-warehouse',              'Warehouse & Logistics',           'part-time'),
  -- mens-bags
  ('mens-backpacks',                   'Backpacks',                       'mens-bags'),
  ('mens-belt-bags',                   'Belt bags, Clutches and Pouches', 'mens-bags'),
  ('mens-briefcases',                  'Briefcases',                      'mens-bags'),
  ('mens-sling-bags',                  'Sling Bags',                      'mens-bags'),
  -- mens-bottoms
  ('mens-chinos',                      'Chinos',                          'mens-bottoms'),
  ('mens-jeans',                       'Jeans',                           'mens-bottoms'),
  ('mens-joggers',                     'Joggers',                         'mens-bottoms'),
  ('mens-new-underwear',               'New Underwear',                   'mens-bottoms'),
  ('mens-shorts',                      'Shorts',                          'mens-bottoms'),
  ('mens-bottoms-sleep-loungewear',    'Sleep and Loungewear',            'mens-bottoms'),
  ('mens-swim-trunks',                 'Swim Trunks & Board Shorts',      'mens-bottoms'),
  ('mens-trousers',                    'Trousers',                        'mens-bottoms'),
  -- mens-footwear
  ('mens-boots',                       'Boots',                           'mens-footwear'),
  ('mens-casual-shoes',                'Casual shoes',                    'mens-footwear'),
  ('mens-dress-shoes',                 'Dress shoes',                     'mens-footwear'),
  ('mens-flipflops-slides',            'Flipflops and Slides',            'mens-footwear'),
  ('mens-shoe-accessories',            'Shoe inserts & accessories',      'mens-footwear'),
  ('mens-sneakers',                    'Sneakers',                        'mens-footwear'),
  -- mens-muslim-wear
  ('mens-muslim-accessories',          'Accessories',                     'mens-muslim-wear'),
  ('baju-melayu',                      'Baju Melayu',                     'mens-muslim-wear'),
  ('jubahs',                           'Jubahs',                          'mens-muslim-wear'),
  ('sarong',                           'Sarong',                          'mens-muslim-wear'),
  ('mens-muslim-tops',                 'Tops',                            'mens-muslim-wear'),
  -- mens-tops-sets
  ('mens-formal-shirts',               'Formal Shirts',                   'mens-tops-sets'),
  ('mens-hoodies',                     'Hoodies',                         'mens-tops-sets'),
  ('mens-sets-coordinates',            'Sets & Coordinates',              'mens-tops-sets'),
  ('mens-tops-sleep-loungewear',       'Sleep and Loungewear',            'mens-tops-sets'),
  ('mens-swim-top-rash-guards',        'Swim Top & Rash Guards',          'mens-tops-sets'),
  ('mens-tshirts-polo-shirts',         'Tshirts & Polo Shirts',           'mens-tops-sets'),
  ('mens-vests',                       'Vests',                           'mens-tops-sets'),
  -- mens-watches-accessories
  ('mens-accessory-holders',           'Accessory holder, box & organisers','mens-watches-accessories'),
  ('mens-beanies',                     'Beanie',                          'mens-watches-accessories'),
  ('mens-belts',                       'Belts',                           'mens-watches-accessories'),
  ('mens-caps-hats',                   'Cap & Hats',                      'mens-watches-accessories'),
  ('mens-cuff-links',                  'Cuff Links',                      'mens-watches-accessories'),
  ('mens-gloves',                      'Gloves',                          'mens-watches-accessories'),
  ('mens-handkerchiefs',               'Handkerchief & Pocket Squares',   'mens-watches-accessories'),
  ('mens-jewelry',                     'Jewelry',                         'mens-watches-accessories'),
  ('mens-scarves',                     'Scarves',                         'mens-watches-accessories'),
  ('mens-socks',                       'Socks',                           'mens-watches-accessories'),
  ('mens-sunglasses',                  'Sunglasses & Eyewear',            'mens-watches-accessories'),
  ('mens-ties',                        'Ties',                            'mens-watches-accessories'),
  ('mens-wallets',                     'Wallets & Card Holders',          'mens-watches-accessories'),
  ('mens-watches',                     'Watches',                         'mens-watches-accessories'),
  -- mobile-gadget-accessories
  ('batteries-power-banks',            'Batteries & Power Banks',         'mobile-gadget-accessories'),
  ('phone-cases-covers',               'Cases & Covers',                  'mobile-gadget-accessories'),
  ('phone-chargers-cables',            'Chargers & Cables',               'mobile-gadget-accessories'),
  ('memory-sd-cards',                  'Memory & SD Cards',               'mobile-gadget-accessories'),
  ('phone-mounts-holders',             'Mounts & Holders',                'mobile-gadget-accessories'),
  ('mobile-accessories-other',         'Other Mobile & Gadget Accessories','mobile-gadget-accessories'),
  ('sim-cards',                        'Sim Cards',                       'mobile-gadget-accessories'),
  -- mobile-phones
  ('android-phones',                   'Android Phones',                  'mobile-phones'),
  ('early-generation-phones',          'Early Generation Mobile Phones',  'mobile-phones'),
  ('iphone',                           'iPhone',                          'mobile-phones'),
  -- photography-accessories
  ('photo-batteries-chargers',         'Batteries & Chargers',            'photography-accessories'),
  ('camera-bags-carriers',             'Camera Bags & Carriers',          'photography-accessories'),
  ('dry-boxes-cabinets',               'Dry Boxes & Cabinets',            'photography-accessories'),
  ('flashes',                          'Flashes',                         'photography-accessories'),
  ('gimbals-stabilisers',              'Gimbals & Stabilisers',           'photography-accessories'),
  ('lighting-studio-equipment',        'Lighting & Studio Equipment',     'photography-accessories'),
  ('photo-accessories-other',          'Other Photography Accessories',   'photography-accessories'),
  ('tripods-monopods',                 'Tripods & Monopods',              'photography-accessories'),
  -- home-services
  ('aircon-services',                  'Aircon Services',                 'home-services'),
  ('home-cleaning',                    'Cleaning',                        'home-services'),
  ('electrical-lighting-wiring',       'Electrical, Lighting & Wiring',   'home-services'),
  ('home-repairs',                     'Home Repairs',                    'home-services'),
  ('movers-delivery',                  'Movers & Delivery',               'home-services'),
  ('home-services-others',             'Others',                          'home-services'),
  ('renovations',                      'Renovations',                     'home-services'),
  -- bicycles-parts
  ('bicycles',                         'Bicycles',                        'bicycles-parts'),
  -- exercise-fitness
  ('cardio-fitness-machines',          'Cardio & Fitness Machines',       'exercise-fitness'),
  ('exercise-mats',                    'Exercise Mats',                   'exercise-fitness'),
  ('toning-stretching-accessories',    'Toning & Stretching Accessories', 'exercise-fitness'),
  ('weights-dumbells',                 'Weights & Dumbells',              'exercise-fitness'),
  -- sports-games
  ('billiards-bowling',                'Billiards & Bowling',             'sports-games'),
  ('golf',                             'Golf',                            'sports-games'),
  ('kites',                            'Kites',                           'sports-games'),
  ('racket-ball-sports',               'Racket & Ball Sports',            'sports-games'),
  ('skates-rollerblades-scooters',     'Skates, Rollerblades & Scooters', 'sports-games'),
  ('water-sports',                     'Water Sports',                    'sports-games'),
  -- gaming-accessories
  ('gaming-cables-chargers',           'Cables & Chargers',               'gaming-accessories'),
  ('gaming-cases-covers',              'Cases & Covers',                  'gaming-accessories'),
  ('controllers',                      'Controllers',                     'gaming-accessories'),
  ('game-gift-cards-accounts',         'Game Gift Cards & Accounts',      'gaming-accessories'),
  ('in-game-products',                 'In-Game Products',                'gaming-accessories'),
  ('interactive-gaming-figures',       'Interactive Gaming Figures',      'gaming-accessories'),
  ('virtual-reality',                  'Virtual Reality',                 'gaming-accessories'),
  -- video-game-consoles
  ('consoles-nintendo',                'Nintendo',                        'video-game-consoles'),
  ('consoles-others',                  'Others',                          'video-game-consoles'),
  ('consoles-playstation',             'PlayStation',                     'video-game-consoles'),
  ('consoles-xbox',                    'Xbox',                            'video-game-consoles'),
  -- video-games
  ('games-nintendo',                   'Nintendo',                        'video-games'),
  ('games-others',                     'Others',                          'video-games'),
  ('games-playstation',                'PlayStation',                     'video-games'),
  ('games-xbox',                       'Xbox',                            'video-games'),
  -- kitchen-appliances
  ('bbq-grills-hotpots',               'BBQ, Grills & Hotpots',           'kitchen-appliances'),
  ('breadmakers',                      'Breadmakers',                     'kitchen-appliances'),
  ('coffee-machines-makers',           'Coffee Machines & Makers',        'kitchen-appliances'),
  ('cookers',                          'Cookers',                         'kitchen-appliances'),
  ('dishwasher',                       'Dishwasher',                      'kitchen-appliances'),
  ('fryers',                           'Fryers',                          'kitchen-appliances'),
  ('hand-stand-mixers',                'Hand & Stand Mixers',             'kitchen-appliances'),
  ('hobs-hoods',                       'Hobs & Hoods',                    'kitchen-appliances'),
  ('ice-cream-makers',                 'Ice-cream Makers',                'kitchen-appliances'),
  ('juicers-blenders-grinders',        'Juicers, Blenders & Grinders',    'kitchen-appliances'),
  ('kettles-airpots',                  'Kettles & Airpots',               'kitchen-appliances'),
  ('kitchen-appliances-other',         'Other Kitchen Appliances',        'kitchen-appliances'),
  ('ovens-toasters',                   'Ovens & Toasters',                'kitchen-appliances'),
  ('refrigerators-freezers',           'Refrigerators & Freezers',        'kitchen-appliances'),
  ('water-purifiers-dispensers',       'Water Purifers & Dispensers',     'kitchen-appliances'),
  ('wine-cellar-storage',              'Wine Cellar & Storage',           'kitchen-appliances'),
  -- tv-entertainment
  ('blu-ray-media-players',            'Blu-Ray & Media Players',         'tv-entertainment'),
  ('entertainment-smart-home',         'Entertainment Systems & Smart Home Devices','tv-entertainment'),
  ('media-streamers-hubs',             'Media Streamers & Hubs',          'tv-entertainment'),
  ('projectors',                       'Projectors',                      'tv-entertainment'),
  ('tv',                               'TV',                              'tv-entertainment'),
  ('tv-parts-accessories',             'TV Parts & Accessories',          'tv-entertainment'),
  -- tablets
  ('tablets-android',                  'Android',                         'tablets'),
  ('tablets-others',                   'Others',                          'tablets'),
  ('tablets-windows',                  'Windows',                         'tablets'),
  ('ipad',                             'iPad',                            'tablets'),
  -- womens-bags-wallets
  ('womens-backpacks',                 'Backpacks',                       'womens-bags-wallets'),
  ('womens-beach-bags',                'Beach Bags',                      'womens-bags-wallets'),
  ('womens-clutches',                  'Clutches',                        'womens-bags-wallets'),
  ('womens-cross-body-bags',           'Cross-body Bags',                 'womens-bags-wallets'),
  ('womens-purses-pouches',            'Purses & Pouches',                'womens-bags-wallets'),
  ('womens-shoulder-bags',             'Shoulder Bags',                   'womens-bags-wallets'),
  ('womens-tote-bags',                 'Tote Bags',                       'womens-bags-wallets'),
  ('womens-wallets',                   'Wallets & Card holders',          'womens-bags-wallets'),
  -- womens-bottoms
  ('womens-jeans-leggings',            'Jeans & Leggings',                'womens-bottoms'),
  ('womens-other-bottoms',             'Other Bottoms',                   'womens-bottoms'),
  ('womens-shorts',                    'Shorts',                          'womens-bottoms'),
  ('womens-skirts',                    'Skirts',                          'womens-bottoms'),
  -- womens-dresses-sets
  ('womens-dresses',                   'Dresses',                         'womens-dresses-sets'),
  ('evening-dresses-gowns',            'Evening Dresses & Gowns',         'womens-dresses-sets'),
  ('jumpsuits',                        'Jumpsuits',                       'womens-dresses-sets'),
  ('rompers',                          'Rompers',                         'womens-dresses-sets'),
  ('womens-sets-coordinates',          'Sets or Coordinates',             'womens-dresses-sets'),
  ('traditional-ethnic-wear',          'Traditional & Ethnic wear',       'womens-dresses-sets'),
  -- womens-footwear
  ('womens-boots',                     'Boots',                           'womens-footwear'),
  ('flats',                            'Flats',                           'womens-footwear'),
  ('womens-flipflops-slides',          'Flipflops and Slides',            'womens-footwear'),
  ('heels',                            'Heels',                           'womens-footwear'),
  ('loafers',                          'Loafers',                         'womens-footwear'),
  ('sandals',                          'Sandals',                         'womens-footwear'),
  ('womens-shoe-inserts',              'Shoe inserts',                    'womens-footwear'),
  ('womens-sneakers',                  'Sneakers',                        'womens-footwear'),
  ('wedges',                           'Wedges',                          'womens-footwear'),
  -- womens-jewelry-organisers
  ('womens-accessory-holders',         'Accessory holder, box & organisers','womens-jewelry-organisers'),
  ('anklets',                          'Anklets',                         'womens-jewelry-organisers'),
  ('body-jewelry',                     'Body Jewelry',                    'womens-jewelry-organisers'),
  ('bracelets',                        'Bracelets',                       'womens-jewelry-organisers'),
  ('brooches',                         'Brooches',                        'womens-jewelry-organisers'),
  ('charms',                           'Charms',                          'womens-jewelry-organisers'),
  ('earrings',                         'Earrings',                        'womens-jewelry-organisers'),
  ('necklaces',                        'Necklaces',                       'womens-jewelry-organisers'),
  ('precious-stones',                  'Precious Stones',                 'womens-jewelry-organisers'),
  ('rings',                            'Rings',                           'womens-jewelry-organisers'),
  -- womens-muslimah-fashion
  ('muslimah-accessories',             'Accessories',                     'womens-muslimah-fashion'),
  ('baju-kurung-sets',                 'Baju Kurung & sets',              'womens-muslimah-fashion'),
  ('muslimah-bottoms',                 'Bottoms',                         'womens-muslimah-fashion'),
  ('muslimah-dresses',                 'Dresses',                         'womens-muslimah-fashion'),
  ('hijabs',                           'Hijabs',                          'womens-muslimah-fashion'),
  ('kaftans-jubahs',                   'Kaftans & Jubahs',                'womens-muslimah-fashion'),
  ('prayer-sets',                      'Prayer Sets',                     'womens-muslimah-fashion'),
  ('muslimah-tops',                    'Tops',                            'womens-muslimah-fashion'),
  -- womens-swimwear
  ('bikinis-swimsuits',                'Bikinis & Swimsuits',             'womens-swimwear'),
  ('muslimah-swimwear',                'Muslimah Swimwear',               'womens-swimwear'),
  ('rash-guard',                       'Rash guard',                      'womens-swimwear'),
  -- womens-tops
  ('blouses',                          'Blouses',                         'womens-tops'),
  ('longsleeves',                      'Longsleeves',                     'womens-tops'),
  ('womens-other-tops',                'Other Tops',                      'womens-tops'),
  ('womens-shirts',                    'Shirts',                          'womens-tops'),
  ('sleeveless',                       'Sleeveless',                      'womens-tops'),
  -- womens-watches-accessories
  ('womens-belts',                     'Belts',                           'womens-watches-accessories'),
  ('womens-gloves',                    'Gloves',                          'womens-watches-accessories'),
  ('hair-accessories',                 'Hair Accessories',                'womens-watches-accessories'),
  ('womens-caps-hats',                 'Hats & Beanies',                  'womens-watches-accessories'),
  ('womens-accessories-other',         'Other Accessories',               'womens-watches-accessories'),
  ('womens-scarves',                   'Scarves',                         'womens-watches-accessories'),
  ('womens-socks-tights',              'Socks & Tights',                  'womens-watches-accessories'),
  ('womens-sunglasses',                'Sunglasses & Eyewear',            'womens-watches-accessories'),
  ('womens-watches',                   'Watches',                         'womens-watches-accessories')
on conflict (slug) do nothing;

-- ── Level 4: Android phone brands + iPhone series ────────────────────────────
insert into public.categories (slug, label, parent_slug) values
  -- android-phones
  ('android-others',    'Android Others',    'android-phones'),
  ('asus',              'Asus',              'android-phones'),
  ('google-pixel',      'Google Pixel',      'android-phones'),
  ('honor',             'Honor',             'android-phones'),
  ('huawei',            'Huawei',            'android-phones'),
  ('infinix',           'Infinix',           'android-phones'),
  ('lg',                'LG',                'android-phones'),
  ('motorola',          'Motorola',          'android-phones'),
  ('nothing-phone',     'Nothing',           'android-phones'),
  ('oppo',              'OPPO',              'android-phones'),
  ('oneplus',           'OnePlus',           'android-phones'),
  ('realme',            'Realme',            'android-phones'),
  ('samsung',           'Samsung',           'android-phones'),
  ('sony',              'Sony',              'android-phones'),
  ('vivo',              'Vivo',              'android-phones'),
  ('xiaomi',            'Xiaomi',            'android-phones'),
  -- iphone
  ('iphone-6',          'iPhone 6 Series',   'iphone'),
  ('iphone-7',          'iPhone 7 Series',   'iphone'),
  ('iphone-8',          'iPhone 8 Series',   'iphone'),
  ('iphone-se',         'iPhone SE Series',  'iphone'),
  ('iphone-x',          'iPhone X Series',   'iphone'),
  ('iphone-11',         'iPhone 11 Series',  'iphone'),
  ('iphone-12',         'iPhone 12 Series',  'iphone'),
  ('iphone-13',         'iPhone 13 Series',  'iphone'),
  ('iphone-14',         'iPhone 14 Series',  'iphone'),
  ('iphone-15',         'iPhone 15 Series',  'iphone'),
  ('iphone-16',         'iPhone 16 Series',  'iphone'),
  ('iphone-17',         'iPhone 17 Series',  'iphone'),
  ('iphone-air',        'iPhone Air Series', 'iphone'),
  ('iphone-others',     'iPhone Others',     'iphone')
on conflict (slug) do nothing;

-- ── Add FK constraint on items.category ──────────────────────────────────────
-- Safe to add now that all valid slugs are seeded.
-- Assumes no existing items rows have invalid category values (fresh dev DB).
alter table public.items
  add constraint items_category_fkey
  foreign key (category) references public.categories(slug);
